# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # Use "pip" for Poetry projects
    directory: "/" # Location of pyproject.toml
    schedule:
      interval: "weekly" # Check for updates once a week
    commit-message:
      # Use a conventional commit message prefix
      prefix: "chore"
